controller_manager_ns: DynamixelProMoveIt
controller_list:
    - name: DynamixelProController
      action_ns: follow_joint_trajectory
      default: true
      joints: 
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
